// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAd5OIAngqc2sOkAEcMM-KKrJ2cx5UFlVc',
    appId: '1:19804179052:web:3e4f61d1f38541c1de2649',
    messagingSenderId: '19804179052',
    projectId: 'gallery-makassar',
    authDomain: 'gallery-makassar.firebaseapp.com',
    storageBucket: 'gallery-makassar.firebasestorage.app',
    measurementId: 'G-1KNRT9E1S2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpWqu52Z0gW8woAjkpX3uGcVAjuTwqvb0',
    appId: '1:19804179052:android:3baaaef42552d8d8de2649',
    messagingSenderId: '19804179052',
    projectId: 'gallery-makassar',
    storageBucket: 'gallery-makassar.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAd5OIAngqc2sOkAEcMM-KKrJ2cx5UFlVc',
    appId: '1:19804179052:web:98bd0f1d06606890de2649',
    messagingSenderId: '19804179052',
    projectId: 'gallery-makassar',
    authDomain: 'gallery-makassar.firebaseapp.com',
    storageBucket: 'gallery-makassar.firebasestorage.app',
    measurementId: 'G-26V1BL2VYL',
  );
}
